# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetCostMatrix <- function(qts1, qts2, disable_normalization = FALSE) {
    .Call(`_squat_GetCostMatrix`, qts1, qts2, disable_normalization)
}

#' QTS Resampling
#'
#' This function performs uniform resampling using SLERP.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#' @param tmin A numeric value specifying the lower bound of the time interval
#'   over which uniform resampling should take place. It must satisfy `tmin >=
#'   min(qts$time)`. Defaults to `NA` in which case it is set to
#'   `min(qts$time)`.
#' @param tmax A numeric value specifying the upper bound of the time interval
#'   over which uniform resampling should take place. It must satisfy `tmax <=
#'   max(qts$time)`. Defaults to `NA` in which case it is set to
#'   `max(qts$time)`.
#' @param nout An integer specifying the size of the uniform grid for time
#'   resampling. Defaults to `0L` in which case it uses the same grid size as
#'   the input QTS.
#' @param disable_normalization A boolean specifying whether quaternion
#'   normalization should be disabled. Defaults to `FALSE` in which case the
#'   function makes sure that quaternions are normalized prior to performing
#'   SLERP interpolation.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions are
#'   uniformly sampled in the range `[tmin, tmax]`.
#'
#' @export
#' @examples
#' TO DO
resample_qts <- function(qts, tmin = NA_real_, tmax = NA_real_, nout = 0L, disable_normalization = FALSE) {
    .Call(`_squat_resample_qts`, qts, tmin, tmax, nout, disable_normalization)
}

#' @export
smooth_qts <- function(qts, alpha = 0.5) {
    .Call(`_squat_smooth_qts`, qts, alpha)
}

#' @export
inner_product_with_yinit <- function(q, qinit) {
    .Call(`_squat_inner_product_with_yinit`, q, qinit)
}

#' @export
calibrate_xy <- function(qts, q0) {
    .Call(`_squat_calibrate_xy`, qts, q0)
}

#' @export
rot_q <- function(axis1, axis2) {
    .Call(`_squat_rot_q`, axis1, axis2)
}

#' QTS Transformation To Angle Time Series
#'
#' This function computes a univariate time series representing the angle
#' between the first and other attitudes.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#' @param disable_normalization A boolean specifying whether quaternion
#'   normalization should be disabled. Defaults to `FALSE`.
#'
#' @return A time series stored as a \code{\link[tibble]{tibble}} with columns
#'   `time` and `angle` in which `angle` measures the angle between the current
#'   rotation and the first one.
#'
#' @export
#' @examples
#' TO DO
qts2angle <- function(qts, disable_normalization = FALSE) {
    .Call(`_squat_qts2angle`, qts, disable_normalization)
}

#' QTS Reorientation
#'
#' This function reorients the quaternions in a QTS for representing attitude
#' with respect to the first time point.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#' @param disable_normalization A boolean specifying whether quaternion
#'   normalization should be disabled. Defaults to `FALSE`.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions measure
#'   attitude with respect to the first time point.
#'
#' @export
#' @examples
#' TO DO
reorient_qts <- function(qts, disable_normalization = FALSE) {
    .Call(`_squat_reorient_qts`, qts, disable_normalization)
}

#' QTS Normalization
#'
#' This function ensures that all quaternions in the time series are unit
#' quaternions.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions are unit
#'   quaternions.
#'
#' @export
#' @examples
#' TO DO
normalize_qts <- function(qts) {
    .Call(`_squat_normalize_qts`, qts)
}

#' QTS Derivative
#'
#' This function computes the first derivative of a quaternion time series with
#' respect to time.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions measure
#'   the rotation to be applied to transform attitude at previous time point to
#'   attitude at the current time point.
#'
#' @export
#' @examples
#' TO DO
derivative_qts <- function(qts) {
    .Call(`_squat_derivative_qts`, qts)
}

#' QTS Logarithm
#'
#' This function computes the logarithm of a quaternion time series as the time
#' series of the quaternion logarithms.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions have been
#'   replaced by their logarithm.
#'
#' @export
#' @examples
#' TO DO
log_qts <- function(qts) {
    .Call(`_squat_log_qts`, qts)
}

#' QTS Exponential
#'
#' This function computes the exponential of a quaternion time series as the
#' time series of the quaternion exponentials.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions have been
#'   replaced by their exponential.
#'
#' @export
#' @examples
#' TO DO
exp_qts <- function(qts) {
    .Call(`_squat_exp_qts`, qts)
}

#' @export
gmean <- function(quaternionSample, maxIterations = 2000L, maxEpsilon = 1.0e-5) {
    .Call(`_squat_gmean`, quaternionSample, maxIterations, maxEpsilon)
}

#' @export
gmedian <- function(quaternionSample, maxIterations = 2000L, maxEpsilon = 1.0e-5) {
    .Call(`_squat_gmedian`, quaternionSample, maxIterations, maxEpsilon)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_squat_RcppExport_registerCCallable', PACKAGE = 'squat')
})
