# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetCostMatrix <- function(x, y) {
    .Call('_squad_GetCostMatrix', PACKAGE = 'squad', x, y)
}

GetSquaredL2Distance <- function(x, y) {
    .Call('_squad_GetSquaredL2Distance', PACKAGE = 'squad', x, y)
}

slerp <- function(v0, v1, t) {
    .Call('_squad_slerp', PACKAGE = 'squad', v0, v1, t)
}

RegularizeGrid <- function(x, y, sizeOut = 0L) {
    .Call('_squad_RegularizeGrid', PACKAGE = 'squad', x, y, sizeOut)
}

