# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetCostMatrix <- function(qts1, qts2, disable_normalization = FALSE) {
    .Call(`_squat_GetCostMatrix`, qts1, qts2, disable_normalization)
}

#' @export
resample_qts <- function(qts, nout = 0L, disable_normalization = FALSE) {
    .Call(`_squat_resample_qts`, qts, nout, disable_normalization)
}

#' QTS Transformation To Angle Time Series
#'
#' This function computes a univariate time series representing the angle
#' between the first and other attitudes.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#' @param disable_normalization A boolean specifying whether quaternion
#'   normalization should be disabled. Defaults to `FALSE`.
#'
#' @return A time series stored as a \code{\link[tibble]{tibble}} with columns
#'   `time` and `angle` in which `angle` measures the angle between the current
#'   rotation and the first one.
#'
#' @export
#' @examples
#' TO DO
qts2angle <- function(qts, disable_normalization = FALSE) {
    .Call(`_squat_qts2angle`, qts, disable_normalization)
}

#' QTS Reorientation
#'
#' This function reorients the quaternions in a QTS for representing attitude
#' with respect to the first time point.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#' @param disable_normalization A boolean specifying whether quaternion
#'   normalization should be disabled. Defaults to `FALSE`.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions measure
#'   attitude with respect to the first time point.
#'
#' @export
#' @examples
#' TO DO
reorient_qts <- function(qts, disable_normalization = FALSE) {
    .Call(`_squat_reorient_qts`, qts, disable_normalization)
}

#' QTS Normalization
#'
#' This function ensures that all quaternions in the time series are unit
#' quaternions.
#'
#' @param qts A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z`.
#'
#' @return A quaternion time series stored as a \code{\link[tibble]{tibble}}
#'   with columns `time`, `w`, `x`, `y` and `z` in which quaternions are unit
#'   quaternions.
#'
#' @export
#' @examples
#' TO DO
normalize_qts <- function(qts) {
    .Call(`_squat_normalize_qts`, qts)
}

#' @export
GetGeodesicMean <- function(quaternionSample, maxIterations = 2000L, maxEpsilon = 1.0e-5) {
    .Call(`_squat_GetGeodesicMean`, quaternionSample, maxIterations, maxEpsilon)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_squat_RcppExport_registerCCallable', PACKAGE = 'squat')
})
